yolo_model:

  config_file:
    name: yolov3-voc-test.cfg
  weight_file:
    name: yolov3-voc-test_3000.weights
  threshold:
    value: 0.3
  detection_classes:
    names:
      - High-screw-M10
      - Low-screw-M10
      - Target-screw-M10
